var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0m9766t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0nkkbfv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1en___f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1uan58j._.js")
R.c("server/chunks/ssr/_174rg3c._.js")
R.c("server/chunks/ssr/node_modules_next_0q-cedu._.js")
R.c("server/chunks/ssr/1daa_next-intl_dist_esm_production_server_react-server_getTranslations_161amqn.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_1j6hl4_._.js")
R.c("server/chunks/ssr/_1cgq6oe._.js")
R.c("server/chunks/ssr/node_modules_zod_v4_classic_external_071rx-x.js")
R.c("server/chunks/ssr/node_modules_next_dist_0kodr5-._.js")
R.m(98063)
module.exports=R.m(98063).exports
